package com.erving.richstep.mock

import com.erving.richstep.domain.tag.domain.Tag
import com.erving.richstep.domain.tag.service.port.TagRepository
import com.erving.richstep.domain.user.domain.User

class FakeTagRepository : TagRepository {

    private var autoGeneratedId: Long = 1L
    private val data: MutableList<Tag> = mutableListOf()

    private fun getIdAfterIncrement(): Long {
        return this.autoGeneratedId++
    }


    override fun save(tag: Tag): Tag {
        return if (tag.id == null) {
            val newTag = tag.copy(id = this.getIdAfterIncrement())
            data.add(newTag)
            newTag
        } else {
            data.removeIf { it.id == tag.id }
            data.add(tag)
            tag
        }
    }

    override fun findAllByUser(user: User): List<Tag> {
        return data.filter { it.user.id == user.id }
    }

    override fun findAllByUserAndNames(
        user: User,
        tagNames: List<String>
    ): List<Tag> {
        return data.filter { it.user.id == user.id && it.name in tagNames }
    }
}