package com.erving.richstep.user.service.port

import com.erving.richstep.user.domain.User

class FakeUserRepository : UserRepository {

    private var autoGeneratedId: Long = 0L
    private val data: MutableList<User> = mutableListOf()

    private fun getIdAfterIncrement(): Long {
        return ++this.autoGeneratedId
    }

    override fun save(user: User): User {
        if (user.id == null) {
            user.id = this.getIdAfterIncrement()
        } else {
            data.removeIf { it.id == user.id }
        }

        this.data.add(user)
        return user
    }


    override fun findById(id: Long): User? {
        return this.data.find { it.id == id }
    }
}